apiVersion: v1
kind: Service
metadata:
  name: jazz-telecom-rag-service
spec:
  type: LoadBalancer
  selector:
    app: jazz-telecom-rag-chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501